services:
  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - internal

  godb-api:
    image: willebergh/godb-api:dev-1.0.9
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "4000:4000"
    networks:
      - internal

volumes:
  mongodb_data:
  redis_data:

networks:
  internal:
